version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: arcadia
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
#    env_file :
#      ./app/back-end-api/.env.dist:
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  php:
    container_name: php
    restart: always
#    command: php -S 0.0.0.0:9000 -t public
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - db
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    build:
      context: ./docker
      dockerfile: Dockerfile-ngnix
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./docker/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
volumes:
  postgres_data:
  mongo_data:
