version: '3.8'

services:
  php:
    container_name: php
    restart: always
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./docker/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: arcadia
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker/build/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
