name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create gcp-key.json (Secure Access)
        # This step retrieves the secret key securely and creates the gcp-key.json file.
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcp-key.json

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: arcadiaproject-429313
          service_account_key: $HOME/gcp-key.json  # Secure access from secret
          export_default_credentials: true

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/mallauryprogra/arcadiaproject_deoliveira:latest
          build-args: |
            HTTP_PORT=8080

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/mallauryprogra/arcadiaproject_deoliveira:latest
          service: arcadia-deoiveira
          region: europe-west9
          platform: managed
          allow_unauthenticated: true
          env_vars: |
            FOO=bar
            ZIP=zap
